services:
  devhabit.api:
    build:
      context: .
      dockerfile: src/DevHabit.Api/Dockerfile
    image: ${DOCKER_REGISTRY-}devhabitapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # Seq #
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "5000:8080"
  devhabit.seq:
    image: datalust/seq:2024.3
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
